### ISSUE TITLE
Mulitibulider and Auto builder ignore the resident permission to place/break blocks.

### ISSUE THREAD

**Issue by haiman233** [Bunnky/SensibleToolboxReborn#12]
Mulitibulider and Auto builder ignore the resident permission to place/break blocks.

**Comment by haiman233** [comment]
including LandMarker , Paint Roller , Combine Hoe and Ender Leash

**Comment by haiman233** [comment]
The same is true for I.R Mod Breaker/ Silky Breaker in ItemRouter.

**Comment by Bunnky** [comment]
Do you mean [Residence](https://www.spigotmc.org/resources/residence-1-7-10-up-to-1-21.11480/)? If so, Slimefun does not have that in its [supported protection plugins](https://github.com/Slimefun/Slimefun4/wiki/Protection-Plugins).

**Comment by haiman233** [comment]
Ok, I'll take the time to test ASkyBlock.

**Comment by Bunnky** [comment]
STB uses dough for all protections. If they aren't in the supported list, protections won't work. This is mostly done so I don't have to manually design the same thing dough already does. With that in mind, I'll close this issue, as I've tested broad protection modules. If there is an issue with an item not respecting a claim or protected land, it's an issue with that item specifically.
