### ISSUE TITLE
When the RedStone Clock is pushed by the piston, it will refresh the block state and become an vanilla block, so as to dupe the redstone block.

### ISSUE THREAD

**Issue by haiman233** [Bunnky/SensibleToolboxReborn#13]
The same is true for other machines that can change the state of blocks.
So suggested that all STB blocks cannot be pushed by the piston.

**Comment by haiman233** [comment]
https://github.com/user-attachments/assets/1abc2324-3442-476d-8e69-fc6b567492c2

**Comment by haiman233** [comment]
like this'

**Comment by haiman233** [comment]
https://github.com/user-attachments/assets/26779286-eec2-4704-8d4f-3ebc7b30916f
Dupe redstone block with network addon

**Comment by haiman233** [comment]
Applicable to all STB blocks.

**Comment by Bunnky** [comment]
Fixed in 191b554
