### ISSUE TITLE
When the UI page of the machine is closed, the power displayed by the energy cell cannot be deducted normally, but is fixed at the moment before the UI is closed.

### ISSUE THREAD

**Issue by haiman233** [Bunnky/SensibleToolboxReborn#2]
Put a fully charged energy cell, such as 50K energy cell, into the machine. When you open the machine page, the energy cell will deduct the power normally. When you close the machine page, the power of the energy cell will be fixed at the moment before closing the UI, but it is normal for the machine to calculate the power in the battery. When the machine stops running due to lack of power, reopen the machine UI page and you will find that the power of the energy cell is still the power displayed when closing the machine page before.

**Comment by Bunnky** [comment]
Fixed in 01f2b1d :)
