### ISSUE TITLE
Version 1.0.2 cannot load Holographic Monitor and Sound Muffer

### ISSUE THREAD

**Issue by haiman233** [Bunnky/SensibleToolboxReborn#5]
Version 1.0.2 cannot load Holographic Monitor and Sound Muffer
MC version：1.20.1
Holographic Monitor cant be loaded in paper and purpur
Sound Muffer seems to be unable to load in paper, but it can be loaded in purpur.
There is no error in STB loading. :(

**Comment by haiman233** [comment]
1.0.0 does not have this problem. :(

**Comment by Bunnky** [comment]
Both the sound Muffler and Holographic Displays require protocol lib, can you post your server log?

**Comment by haiman233** [comment]
> Both the sound Muffler and Holographic Displays require protocol lib, can you post your server log?

oh,my paper server forgot to install the protocol lib,but the Holographic Displays still couldnt be loaded.

I have checked my server log, They're all fine

**Comment by haiman233** [comment]
Sound Muffler can be loaded normally.

**Comment by Bunnky** [comment]
Ok, you said Holographic Displays still couldn't be loaded?

**Comment by haiman233** [comment]
yes

**Comment by Bunnky** [comment]
Another dependancy, however [Holographic Displays](https://dev.bukkit.org/projects/holographic-displays) is no longer supported, and does not work on atleast 1.20.6. Due to this, I'll find a more commonly used Holograms plugin to hook into, maybe CMI or Essentials if I can since they are more common.

**Comment by Bunnky** [comment]
Fixed in a1a17aa

Now using [DecentHolograms ](https://www.spigotmc.org/resources/decentholograms-1-8-1-21-1-papi-support-no-dependencies.96927/)API as a replacement for Holographic Displays. A message has been added to indicate if DecentHolograms isn't installed as well.
